### ISSUE TITLE
relation "users_profile" does not exist

### ISSUE THREAD

**Issue by LSY310** [OZ-Coding-School/oz_03_main-006-BE#15]
app-1  | The above exception was the direct cause of the following exception:
app-1  | 
app-1  | Traceback (most recent call last):
app-1  |   File "/py/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
app-1  |     response = get_response(request)
app-1  |                ^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
app-1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
app-1  |     return view_func(*args, **kwargs)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
app-1  |     return self.dispatch(request, *args, **kwargs)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
app-1  |     response = self.handle_exception(exc)
app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
app-1  |     self.raise_uncaught_exception(exc)
app-1  |   File "/py/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
app-1  |     raise exc
app-1  |   File "/py/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
app-1  |     response = handler(request, *args, **kwargs)
app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
app-1  |     return func(*args, **kwargs)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/app/boards/views.py", line 31, in posts
app-1  |     if serializer.is_valid(raise_exception=True):
app-1  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/rest_framework/serializers.py", line 223, in is_valid
app-1  |     self._validated_data = self.run_validation(self.initial_data)
app-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/rest_framework/serializers.py", line 442, in run_validation
app-1  |     value = self.to_internal_value(data)
app-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/rest_framework/serializers.py", line 499, in to_internal_value
app-1  |     validated_value = field.run_validation(primitive_value)
app-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/rest_framework/relations.py", line 155, in run_validation
app-1  |     return super().run_validation(data)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/rest_framework/fields.py", line 538, in run_validation
app-1  |     value = self.to_internal_value(data)
app-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/rest_framework/relations.py", line 259, in to_internal_value
app-1  |     return queryset.get(pk=data)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
app-1  |     num = len(clone)
app-1  |           ^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
app-1  |     self._fetch_all()
app-1  |   File "/py/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
app-1  |     self._result_cache = list(self._iterable_class(self))
app-1  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
app-1  |     results = compiler.execute_sql(
app-1  |               ^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
app-1  |     cursor.execute(sql, params)
app-1  |   File "/py/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
app-1  |     return super().execute(sql, params)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
app-1  |     return self._execute_with_wrappers(
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
app-1  |     return executor(sql, params, many, context)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/py/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
app-1  |     with self.db.wrap_database_errors:
app-1  |   File "/py/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
app-1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
app-1  |   File "/py/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
app-1  |     return self.cursor.execute(sql, params)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  | django.db.utils.ProgrammingError: relation "users_profile" does not exist
app-1  | LINE 1: ...le"."password", "users_profile"."created_at" FROM "users_pro...

난... posts에서 users_profile을 사용하는 부분이 없는데... 도대체 어디서 오류가 계속 나는것인가...

**Comment by LSY310** [comment]
db접속해서 확인결과 
Schema |             Name              | Type  |   Owner   
--------+-------------------------------+-------+-----------
 public | account_emailaddress          | table | han_cycle
 public | account_emailconfirmation     | table | han_cycle
 public | auth_group                    | table | han_cycle
 public | auth_group_permissions        | table | han_cycle
 public | auth_permission               | table | han_cycle
 public | auth_user                     | table | han_cycle
 public | auth_user_groups              | table | han_cycle
 public | auth_user_user_permissions    | table | han_cycle
 public | authtoken_token               | table | han_cycle
 public | boards_comment                | table | han_cycle
 public | boards_image                  | table | han_cycle
 public | boards_picture                | table | han_cycle
 public | boards_post                   | table | han_cycle
 public | boards_post_thumbnail         | table | han_cycle
 public | django_admin_log              | table | han_cycle
 public | django_content_type           | table | han_cycle
 public | django_migrations             | table | han_cycle
 public | django_session                | table | han_cycle
table이 없음

**Comment by LSY310** [comment]
users_users 테이블이 있길래 model을 profile에서 users로 수정해서 실행해보니
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/mac/oz_03_main-006-BE/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 376, in __repr__
    data = list(self[: REPR_OUTPUT_SIZE + 1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/oz_03_main-006-BE/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 400, in __iter__
    self._fetch_all()
  File "/Users/mac/oz_03_main-006-BE/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/oz_03_main-006-BE/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/oz_03_main-006-BE/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/mac/oz_03_main-006-BE/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/oz_03_main-006-BE/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/oz_03_main-006-BE/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/oz_03_main-006-BE/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/Users/mac/oz_03_main-006-BE/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/mac/oz_03_main-006-BE/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/oz_03_main-006-BE/.venv/lib/python3.12/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: column boards_post.user_id does not exist
LINE 1: SELECT "boards_post"."id", "boards_post"."user_id", "boards_...
이런오류 발생

**Comment by LSY310** [comment]
users.users.user_id 를 찾지 못해 생긴 오류 users모델에서 user가 의미하는건 무엇인가??

**Comment by LSY310** [comment]
erd랑 다르게 되어있어서 그런거같오 보니까 인증부분때문에 use모델 끌고와서 만든거같더라궁,,

**Comment by yoonju977** [comment]
유저모델 erd와 일치 시키는 작업 수행
